name: Marion Newlevant - github
markdown: redcarpet
pygments: true

# I would LIKE to have source in _source, but github doesn't seem to work with that...
exclude: [Gemfile, Gemfile.lock, Gruntfile.js, LICENSE, node_modules, package.json, README.md, sass]
